<?xml version="1.0"?>
<robot name="planesil" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <macro name="cylinder_inertia" params="m r h">
        <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
            iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
            izz="${m*r*r/2}"
        />
    </macro>

    <macro name="box_inertia" params="m x y z">
        <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
            iyy="${m*(x*x+z*z)/12}" iyz = "0"
            izz="${m*(x*x+z*z)/12}"
        />
    </macro>

    <macro name="sphere_inertia" params="m r">
        <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
            iyy="${2*m*r*r/5}" iyz = "0"
            izz="${2*m*r*r/5}"
        />
    </macro>

    <xacro:macro name="joint_transmission" params= "joint_name">
        <transmission name="${joint_name}_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${joint_name}_joint">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${joint_name}_servo">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>10</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>


    <xacro:macro name="wing" params="name left">
        <link name="${name}_wing">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/> 
                <mass value="${wingMass}"/>
                <xacro:box_inertia m="${wingMass}" x="${wingX}" y="${wingY}" z="${wingZ}"/>
            </inertial>

            <collision> 
                <origin xyz="0 0 0" rpy="0 0 0"/>  
                <geometry> 
                    <box size="${wingX} ${wingY} ${wingZ}"/> 
                </geometry> 
            </collision>

            <visual> 
                <origin xyz="0 0 0" rpy="0 0 0"/> 
                <geometry> 
                    <box size="${wingX} ${wingY} ${wingZ}"/> 
                </geometry> 
                <material name="red"/>
            </visual>
        </link>

        <joint name="${name}_wing_joint" type="continuous">
            <parent link="body"/>
            <child link="${name}_wing"/>
            <origin xyz="0 ${left * (bodyY/2 + wingY/2)} 0" rpy="0 0 0"/>
            <axis xyz="0 1 0" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="landingGear" params="name front">
        <link name="${name}_landingGear">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${landingGearMass}"/>
                <xacro:box_inertia m="${landingGearMass}" x="${landingGearX}" y="${landingGearY}" z="${landingGearZ}"/>
            </inertial>

            <collision> 
                <origin xyz="0 0 0" rpy="0 0 0"/> 
                <geometry> 
                    <box size="${landingGearX} ${landingGearY} ${landingGearZ}"/> 
                </geometry> 
            </collision>

            <visual> 
                <origin xyz="0 0 0" rpy="0 0 0"/> 
                <geometry> 
                    <box size="${landingGearX} ${landingGearY} ${landingGearZ}"/> 
                </geometry> 
                <material name="orange"/>
            </visual>
        </link>
        
        <joint name="${name}_landingGear_joint" type="fixed">
            <parent link="body"/>
            <child link="${name}_landingGear"/>
            <origin xyz="${front * (bodyX/2 - landingGearX/2)} 0 ${bodyZ/2-landingGearZ/2}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="wheel" params="name front left">
         <link name="${name}_wheel">
            <collision>
                <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
                <geometry>
                <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
                <geometry>
                <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
                </geometry>
                <material name="black"/>
            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
                <mass value="${wheelMass}"/>
                <xacro:cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
            </inertial>
        </link>

        <gazebo reference="${name}_wheel">
            <mu1 value="1.0"/>
            <mu2 value="1.0"/>
            <kp  value="10000000.0" />
            <kd  value="1.0" />
            <fdir1 value="1 0 0"/>
            <material>Gazebo/Black</material>
        </gazebo>


        <joint name="${name}_wheel_hinge" type="continuous">

            <xacro:if value="${front == 1}">
                <parent link="front_landingGear"/>
            </xacro:if>
            <xacro:unless value="${front == 1}">
                <parent link="back_landingGear"/>
            </xacro:unless>

            <child link="${name}_wheel"/>
            <origin xyz="0 ${left * (landingGearY/2 + wheelWidth/2)} ${-landingGearZ/2}" rpy="0 0 0" />
            <axis xyz="0 1 0" rpy="0 0 0" />
            <limit effort="100" velocity="100"/>
            <joint_properties damping="0.0" friction="0.5"/>
        </joint>
    </xacro:macro>


<!-- 
xacro template:
<?xml version="1.0"?>
<robot name="planesil" xmlns:xacro="http://www.ros.org/wiki/xacro">

</robot> -->

</robot>
