<?xml version="1.0"?>
<robot name="planesil" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find planesim_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find planesim_description)/urdf/macros.xacro" />
    
    <xacro:property name="PI" value="3.14"/>

    <xacro:property name="bodyY" value="0.5"/>
    <xacro:property name="bodyX" value="6"/>
    <xacro:property name="bodyZ" value="0.5"/>
    <xacro:property name="bodyMass" value="300"/>

    <xacro:property name="wingY" value="5"/>
    <xacro:property name="wingX" value="1"/>
    <xacro:property name="wingZ" value="${bodyZ/4}"/>
    <xacro:property name="wingMass" value="100"/>

    <xacro:property name="landingGearY" value="${bodyY}"/>
    <xacro:property name="landingGearX" value="0.125"/>
    <xacro:property name="landingGearZ" value="1"/>
    <xacro:property name="landingGearMass" value="10"/>

    <xacro:property name="wheelWidth" value="0.1"/>
    <xacro:property name="wheelRadius" value="0.25"/>
    <xacro:property name="wheelMass" value="5"/>

    <xacro:property name="propellorBlockX" value="0.25"/>
    <xacro:property name="propellorBlockY" value="${bodyY/2}"/>
    <xacro:property name="propellorBlockZ" value="${bodyZ/2}" />
    <xacro:property name="propellorBlockMass" value="5"/>

    <xacro:property name="propellorX" value="1.5"/>      <!-- Length of blade -->
    <xacro:property name="propellorY" value="0.2"/>   <!-- Width of blade -->
    <xacro:property name="propellorZ" value="0.1"/>    <!-- Thickness of blade -->
    <xacro:property name="propellorMass" value="2"/>

    <!-- X axis is down the runway -->
    <!-- Y axis is to the left of the runway, looking down -->
    <!-- Z axis is up -->

    <link name="body">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${bodyMass}"/>
            <xacro:box_inertia m="${bodyMass}" x="${bodyX}" y="${bodyY}" z="${bodyZ}"/>
        </inertial>

        <collision> 
            <origin xyz="0 0 0" rpy="0 0 0"/> 
            <geometry> 
                <box size="${bodyX} ${bodyY} ${bodyZ}"/> 
            </geometry> 
        </collision>

        <visual> 
            <origin xyz="0 0 0" rpy="0 0 0"/> 
            <geometry> 
                <box size="${bodyX} ${bodyY} ${bodyZ}"/> 
            </geometry> 
            <material name="orange"/>
        </visual>
    </link>

    <gazebo reference="body">
        <material>Gazebo/Orange</material>
    </gazebo>

    <link name="base_link"/>
    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="body"/>
    </joint>


    <xacro:wing name="left" left="1"/>
    <xacro:wing name="right" left="-1"/>

    <xacro:landingGear name="front" front="1"/>
    <xacro:landingGear name="back" front="-1"/>

    <xacro:wheel name="frontLeft_wheel" front="1" left="1" />
    <xacro:wheel name="frontRight_wheel" front="1" left="-1" />
    <xacro:wheel name="backLeft_wheel" front="-1" left="1" />
    <xacro:wheel name="backRight_wheel" front="-1" left="-1" />

    <link name="propellorBlock">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${propellorBlockMass}"/>
            <xacro:box_inertia m="${propellorBlockMass}" x="${propellorBlockX}" y="${propellorBlockY}" z="${propellorBlockZ}"/>
        </inertial>

        <collision> 
            <origin xyz="0 0 0" rpy="0 0 0"/> 
            <geometry> 
                <box size="${propellorBlockX} ${propellorBlockY} ${propellorBlockZ}"/> 
            </geometry> 
        </collision>

        <visual> 
            <origin xyz="0 0 0" rpy="0 0 0"/> 
            <geometry> 
                <box size="${propellorBlockX} ${propellorBlockY} ${propellorBlockZ}"/> 
            </geometry> 
            <material name="orange"/>
        </visual>
    </link>

    <gazebo reference="propellorBlock">
        <material>Gazebo/Orange</material>
    </gazebo>

    <joint name="propellorBlock_joint" type="fixed">
        <parent link="body"/>
        <child link="propellorBlock"/>
        <origin xyz="${bodyX/2 + propellorBlockX/2} 0 0" rpy="0 0 0"/>
    </joint>

    <link name="propellor">
        <inertial>
            <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
            <mass value="${propellorMass}"/>
            <xacro:box_inertia m="${propellorMass}" x="${propellorX}" y="${propellorY}" z="${propellorZ}"/>
        </inertial>

        <collision> 
            <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
            <geometry> 
                <box size="${propellorX} ${propellorY} ${propellorZ}"/> 
            </geometry> 
        </collision>

        <visual> 
            <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
            <geometry> 
                <box size="${propellorX} ${propellorY} ${propellorZ}"/> 
            </geometry> 
            <material name="blue"/>
        </visual>
    </link>

    <gazebo reference="propellor">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="propellor_joint" type="continuous">
        <parent link="propellorBlock" />
        <child link="propellor" />
        <origin xyz="${propellorBlockX/2 + propellorZ/2} 0 0" rpy="0 0 0"/>
    </joint>

    <xacro:joint_transmission name="propellor_transmission" joint_name="propellor_joint"/>

    <xacro:property name="counterWeightCoGXOffset" value="${((propellorBlockMass * propellorBlockX/2) + propellorMass * (propellorBlockX/2 + propellorZ/2))
                                                /(propellorBlockMass + propellorMass)}"/> <!-- Center of gravity from the edge of the body -->
    <link name="counterWeight">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${propellorBlockMass + propellorMass}"/>
            <xacro:box_inertia m="${propellorBlockMass + propellorMass}" x="${2 * counterWeightCoGXOffset}" y="${bodyY}" z="${bodyZ}"/>
        </inertial>

        <collision> 
            <origin xyz="0 0 0" rpy="0 0 0"/> 
            <geometry> 
                <box size="${2 * counterWeightCoGXOffset} ${bodyY} ${bodyZ}"/> 
            </geometry> 
        </collision>

        <visual> 
            <origin xyz="0 0 0" rpy="0 0 0"/> 
            <geometry> 
                <box size="${2 * counterWeightCoGXOffset} ${bodyY} ${bodyZ}"/> 
            </geometry> 
            <material name="orange"/>
        </visual>
    </link>

    <gazebo reference="propellorBlock">
        <material>Gazebo/Orange</material>
    </gazebo>

    <joint name="counterWeight_joint" type="fixed">
        <parent link="body"/>
        <child link="counterWeight"/>
        <origin xyz="${-(bodyX/2 + counterWeightCoGXOffset)} 0 0" rpy="0 0 0"/>
    </joint>

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/planesim</robotNamespace>
        </plugin>
    </gazebo>

</robot>